function onStart()
	for k, v in ipairs(getElementsByType("vehicle")) do
		loadHandling(v)
	end
end
addEventHandler("onResourceStart", resourceRoot, onStart)

function loadHandling(element)
	if getElementModel(element) == 602 then
		setVehicleHandling(element, "mass", 1600)
		setVehicleHandling(element, "turnMass", 3000)
		setVehicleHandling(element, "dragCoeff", 1.8)
		setVehicleHandling(element, "centerOfMass", { 0, 0.50, -0.3 } )
		setVehicleHandling(element, "percentSubmerged", 75)
		setVehicleHandling(element, "tractionMultiplier", 1.05)
		setVehicleHandling(element, "tractionLoss", 1.1)
		setVehicleHandling(element, "tractionBias", 0.497)
		setVehicleHandling(element, "numberOfGears", 5)
		setVehicleHandling(element, "maxVelocity", 240)
		setVehicleHandling(element, "engineAcceleration", 40)
		setVehicleHandling(element, "engineInertia", 60)
		setVehicleHandling(element, "driveType", "awd")
		setVehicleHandling(element, "engineType", "petrol")
		setVehicleHandling(element, "brakeDeceleration", 85)
		setVehicleHandling(element, "ABS", false)
		setVehicleHandling(element, "steeringLock", 45)
		setVehicleHandling(element, "modelFlags", 0x00002000)
		setVehicleHandling(element, "headLight", 0)
		setVehicleHandling(element, "tailLight", 1)
		setVehicleHandling(element, "animGroup", 0)
		setVehicleHandling(element, "suspensionForceLevel", 1.1)
		--setVehicleHandling(element, "suspensionUpperLimit", 0.38)
		setVehicleHandling(element, "suspensionLowerLimit", -0.1)
		setVehicleHandling(element, "suspensionHighSpeedDamping", 0.5)
		--setVehicleHandling(element, "suspensionDamping", )
	elseif getElementModel(element) == 480 then
		setVehicleHandling(element, "mass", 1400)
		setVehicleHandling(element, "turnMass", 2200)
		setVehicleHandling(element, "dragCoeff", 2.2)
		setVehicleHandling(element, "centerOfMass", { 0, 0.1, -0.2 } )
		setVehicleHandling(element, "percentSubmerged", 75)
		setVehicleHandling(element, "tractionMultiplier", 0.82)
		setVehicleHandling(element, "tractionLoss", 1)
		setVehicleHandling(element, "tractionBias", 0.5)
		setVehicleHandling(element, "numberOfGears", 5)
		setVehicleHandling(element, "maxVelocity", 340)
		setVehicleHandling(element, "engineAcceleration", 27)
		setVehicleHandling(element, "engineInertia", 10)
		setVehicleHandling(element, "driveType", "awd")
		setVehicleHandling(element, "engineType", "diesel")
		setVehicleHandling(element, "brakeDeceleration", 10.03)
		setVehicleHandling(element, "ABS", false)
		setVehicleHandling(element, "steeringLock", 50)
		setVehicleHandling(element, "suspensionForceLevel", 0.7)
		setVehicleHandling(element, "suspensionDamping", 0.14)
		setVehicleHandling(element, "suspensionHighSpeedDamping", 3)
		setVehicleHandling(element, "suspensionUpperLimit", 0.28)
		setVehicleHandling(element, "suspensionLowerLimit", -0.15)
		setVehicleHandling(element, "suspensionFrontRearBias", 0.5)
		setVehicleHandling(element, "suspensionAntiDiveMultiplier", 0.3)
		setVehicleHandling(element, "seatOffsetDistance", 0.25)
		setVehicleHandling(element, "collisionDamageMultiplier", 0.60)
		setVehicleHandling(element, "monetary", 35000)
		setVehicleHandling(element, "modelFlags", 0x40002800)
		setVehicleHandling(element, "handlingFlags", 0x10308803)
		setVehicleHandling(element, "headLight", 1)
		setVehicleHandling(element, "tailLight", 1)
		setVehicleHandling(element, "animGroup", 19)
	elseif getElementModel(element) == 445 then
		setVehicleHandling(element, "mass", 2600)
		setVehicleHandling(element, "turnMass", 4700)
		setVehicleHandling(element, "dragCoeff", 2)
		setVehicleHandling(element, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(element, "percentSubmerged", 75)
		setVehicleHandling(element, "tractionMultiplier", 1.27)
		setVehicleHandling(element, "tractionLoss", 0.85)
		setVehicleHandling(element, "tractionBias", 0.49)
		setVehicleHandling(element, "numberOfGears", 5)
		setVehicleHandling(element, "maxVelocity", 205)
		setVehicleHandling(element, "engineAcceleration", 40)
		setVehicleHandling(element, "engineInertia", 44)
		setVehicleHandling(element, "driveType", "awd")
		setVehicleHandling(element, "engineType", "petrol")
		setVehicleHandling(element, "brakeDeceleration", 181)
		setVehicleHandling(element, "ABS", false)
		setVehicleHandling(element, "steeringLock", 50.0)
		setVehicleHandling(element, "suspensionForceLevel", 0.55)
		setVehicleHandling(element, "suspensionDamping", 0.4)
		setVehicleHandling(element, "suspensionHighSpeedDamping", 3)
		setVehicleHandling(element, "suspensionUpperLimit", 0.1)
		setVehicleHandling(element, "suspensionLowerLimit", -0.1)
		setVehicleHandling(element, "suspensionFrontRearBias", 0.55)
		setVehicleHandling(element, "suspensionAntiDiveMultiplier", 0.5)
		setVehicleHandling(element, "seatOffsetDistance", 0.2)
		setVehicleHandling(element, "collisionDamageMultiplier", 0.60)
		setVehicleHandling(element, "monetary", 35000)
		setVehicleHandling(element, "modelFlags", 0x400000)
		setVehicleHandling(element, "handlingFlags", 0x12010000)
		setVehicleHandling(element, "headLight", 0)
		setVehicleHandling(element, "tailLight", 1)
		setVehicleHandling(element, "animGroup", 0)
		setVehicleHandling(element, "modelFlags", 0x00002000)
	elseif getElementModel(element) == 489 then
		--setVehicleHandling(element, "suspensionUpperLimit", 1)
		--setVehicleHandling(element, "monetary", 50000)
		--setVehicleHandling(element, "percentSubmerged", 20)
		--setVehicleHandling(element, "percentSubmerged", 75)
		setVehicleHandling(element, "handlingFlags", 0x4004000)
		setVehicleHandling(element, "centerOfMass", { 0, -0.32, -0.32 } )
		setVehicleHandling(element, "suspensionLowerLimit", -0.2)
	elseif getElementModel(element) == 596 then
		setVehicleHandling(element, "mass", 2200)
		setVehicleHandling(element, "turnMass", 3400)
		setVehicleHandling(element, "dragCoeff", 2)
		setVehicleHandling(element, "centerOfMass", { 0, 0.22, -0.31 } )
		setVehicleHandling(element, "percentSubmerged", 75)
		setVehicleHandling(element, "tractionMultiplier", 1.4)
		setVehicleHandling(element, "tractionLoss", 0.72)
		setVehicleHandling(element, "tractionBias", 0.47)
		setVehicleHandling(element, "numberOfGears", 5)
		setVehicleHandling(element, "maxVelocity", 235)
		setVehicleHandling(element, "engineAcceleration", 32)
		setVehicleHandling(element, "engineInertia", 22)
		setVehicleHandling(element, "driveType", "awd")
		setVehicleHandling(element, "engineType", "petrol")
		setVehicleHandling(element, "brakeDeceleration", 181)
		setVehicleHandling(element, "ABS", false)
		setVehicleHandling(element, "steeringLock", 48.0)
		setVehicleHandling(element, "suspensionForceLevel", 0.7)
		setVehicleHandling(element, "suspensionDamping", 0.4)
		setVehicleHandling(element, "suspensionHighSpeedDamping", 0)
		setVehicleHandling(element, "suspensionUpperLimit", 0.34)
		setVehicleHandling(element, "suspensionLowerLimit", -0.3)
		setVehicleHandling(element, "suspensionFrontRearBias", 0.55)
		setVehicleHandling(element, "suspensionAntiDiveMultiplier", 0.34)
		setVehicleHandling(element, "seatOffsetDistance", 0.2)
		setVehicleHandling(element, "collisionDamageMultiplier", 0.25)
		setVehicleHandling(element, "monetary", 35000)
		setVehicleHandling(element, "modelFlags", 0x400000)
		setVehicleHandling(element, "handlingFlags", 0x12010000)
		setVehicleHandling(element, "headLight", 0)
		setVehicleHandling(element, "tailLight", 1)
		setVehicleHandling(element, "animGroup", 0)
				-- Police 2 #Szaby ;)
	elseif getElementModel(element) == 597 then
		setVehicleHandling(element, "mass", 1500)
		setVehicleHandling(element, "turnMass", 3200)
		setVehicleHandling(element, "dragCoeff", 1.4)
		setVehicleHandling(element, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(element, "percentSubmerged", 75)
		setVehicleHandling(element, "tractionMultiplier", 1.5)
		setVehicleHandling(element, "tractionLoss", 0.8)
		setVehicleHandling(element, "tractionBias", 0.465)
		setVehicleHandling(element, "numberOfGears", 5)
		setVehicleHandling(element, "maxVelocity", 232)
		setVehicleHandling(element, "engineAcceleration", 65)
		setVehicleHandling(element, "engineInertia", 50)
		setVehicleHandling(element, "driveType", "awd")
		setVehicleHandling(element, "engineType", "petrol")
		setVehicleHandling(element, "brakeDeceleration", 65)
		setVehicleHandling(element, "ABS", false)
		setVehicleHandling(element, "steeringLock", 52)
		setVehicleHandling(element, "suspensionForceLevel", 1.8)
		setVehicleHandling(element, "suspensionDamping", 0.9)
		setVehicleHandling(element, "suspensionHighSpeedDamping", 0.1)
		setVehicleHandling(element, "suspensionUpperLimit", 0.3)
		setVehicleHandling(element, "suspensionLowerLimit", -0.12)
		setVehicleHandling(element, "suspensionFrontRearBias", 0.55)
		setVehicleHandling(element, "suspensionAntiDiveMultiplier", 0.5)
		setVehicleHandling(element, "seatOffsetDistance", 0.5)
		setVehicleHandling(element, "collisionDamageMultiplier", 0.45)
		setVehicleHandling(element, "monetary", 30000)
		setVehicleHandling(element, "modelFlags", 0x40000001)
		setVehicleHandling(element, "handlingFlags", 0x10308803)
		setVehicleHandling(element, "headLight", 0)
		setVehicleHandling(element, "tailLight", 1)
		setVehicleHandling(element, "animGroup", 0)			-- Police 3 #Szaby ;)
	elseif getElementModel(element) == 598 then
		setVehicleHandling(element, "mass", 1500)
		setVehicleHandling(element, "turnMass", 3200)
		setVehicleHandling(element, "dragCoeff", 1.4)
		setVehicleHandling(element, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(element, "percentSubmerged", 75)
		setVehicleHandling(element, "tractionMultiplier", 1.5)
		setVehicleHandling(element, "tractionLoss", 0.8)
		setVehicleHandling(element, "tractionBias", 0.465)
		setVehicleHandling(element, "numberOfGears", 5)
		setVehicleHandling(element, "maxVelocity", 240)
		setVehicleHandling(element, "engineAcceleration", 95)
		setVehicleHandling(element, "engineInertia", 70)
		setVehicleHandling(element, "driveType", "awd")
		setVehicleHandling(element, "engineType", "petrol")
		setVehicleHandling(element, "brakeDeceleration", 50)
		setVehicleHandling(element, "ABS", false)
		setVehicleHandling(element, "steeringLock", 52)
		setVehicleHandling(element, "suspensionForceLevel", 1.8)
		setVehicleHandling(element, "suspensionDamping", 0.9)
		setVehicleHandling(element, "suspensionHighSpeedDamping", 0.1)
		setVehicleHandling(element, "suspensionUpperLimit", 0.3)
		setVehicleHandling(element, "suspensionLowerLimit", -0.12)
		setVehicleHandling(element, "suspensionFrontRearBias", 0.55)
		setVehicleHandling(element, "suspensionAntiDiveMultiplier", 0.5)
		setVehicleHandling(element, "seatOffsetDistance", 0.5)
		setVehicleHandling(element, "collisionDamageMultiplier", 0.45)
		setVehicleHandling(element, "monetary", 30000)
		setVehicleHandling(element, "modelFlags", 0x40000001)
		setVehicleHandling(element, "handlingFlags", 0x10308803)
		setVehicleHandling(element, "headLight", 0)
		setVehicleHandling(element, "tailLight", 1)
		setVehicleHandling(element, "animGroup", 0)	
	elseif getElementModel(element) == 547 then
		setVehicleHandling(element, "mass", 1500)
		setVehicleHandling(element, "turnMass", 3200)
		setVehicleHandling(element, "dragCoeff", 1.4)
		setVehicleHandling(element, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(element, "percentSubmerged", 75)
		setVehicleHandling(element, "tractionMultiplier", 1.5)
		setVehicleHandling(element, "tractionLoss", 0.8)
		setVehicleHandling(element, "tractionBias", 0.465)
		setVehicleHandling(element, "numberOfGears", 5)
		setVehicleHandling(element, "maxVelocity", 200)
		setVehicleHandling(element, "engineAcceleration", 20)
		setVehicleHandling(element, "engineInertia", 10)
		setVehicleHandling(element, "driveType", "awd")
		setVehicleHandling(element, "modelFlags", 0x00002000)

		setVehicleHandling(element, "brakeDeceleration", 50)
		setVehicleHandling(element, "steeringLock", 30)
		
	elseif getElementModel(element) == 540 then
		setVehicleHandling(element, "mass", 2000)
		setVehicleHandling(element, "turnMass", 3500)
		setVehicleHandling(element, "dragCoeff", 1.8)
		setVehicleHandling(element, "centerOfMass", { 0, 0.50, -0.3 } )
		setVehicleHandling(element, "percentSubmerged", 75)
		setVehicleHandling(element, "tractionMultiplier", 1.05)
		setVehicleHandling(element, "tractionLoss", 0.9)
		setVehicleHandling(element, "tractionBias", 0.497)
		setVehicleHandling(element, "numberOfGears", 5)
		setVehicleHandling(element, "maxVelocity", 200)
		setVehicleHandling(element, "engineAcceleration", 26)
		setVehicleHandling(element, "engineInertia", 50)
		setVehicleHandling(element, "driveType", "awd")
		setVehicleHandling(element, "engineType", "petrol")
		setVehicleHandling(element, "brakeDeceleration", 80)
		setVehicleHandling(element, "ABS", false)
		setVehicleHandling(element, "steeringLock", 35)
		setVehicleHandling(element, "monetary", 25000)
		setVehicleHandling(element, "headLight", 0)
		setVehicleHandling(element, "tailLight", 1)
		setVehicleHandling(element, "animGroup", 0)
		setVehicleHandling(element, "suspensionForceLevel", 1.75)
		setVehicleHandling(element, "suspensionUpperLimit", 0.38)
		setVehicleHandling(element, "suspensionLowerLimit", -0.2)
		setVehicleHandling(element, "suspensionFrontRearBias", 0.65)
	elseif getElementModel(element) == 565 then
		setVehicleHandling(element, "mass", 2600)
		setVehicleHandling(element, "turnMass", 4700)
		setVehicleHandling(element, "dragCoeff", 2)
		setVehicleHandling(element, "centerOfMass", { 0, 0.20, -0.3 } )
		setVehicleHandling(element, "percentSubmerged", 75)
		setVehicleHandling(element, "tractionMultiplier", 1.27)
		setVehicleHandling(element, "tractionLoss", 0.72)
		setVehicleHandling(element, "tractionBias", 0.472)
		setVehicleHandling(element, "numberOfGears", 5)
		setVehicleHandling(element, "maxVelocity", 242)
		setVehicleHandling(element, "engineAcceleration", 62)
		setVehicleHandling(element, "engineInertia", 51)
		setVehicleHandling(element, "driveType", "awd")
		setVehicleHandling(element, "engineType", "petrol")
		setVehicleHandling(element, "brakeDeceleration", 181)
		setVehicleHandling(element, "ABS", false)
		setVehicleHandling(element, "steeringLock", 47.0)
		setVehicleHandling(element, "suspensionForceLevel", 0.8)
		setVehicleHandling(element, "suspensionDamping", 0.15)
		setVehicleHandling(element, "suspensionHighSpeedDamping", 0.25)
		setVehicleHandling(element, "suspensionUpperLimit", 0.12)
		setVehicleHandling(element, "suspensionLowerLimit", -0.24)
		setVehicleHandling(element, "suspensionFrontRearBias", 0.55)
		setVehicleHandling(element, "suspensionAntiDiveMultiplier", 0.5)
		setVehicleHandling(element, "seatOffsetDistance", 0.2)
		setVehicleHandling(element, "collisionDamageMultiplier", 0.60)
		setVehicleHandling(element, "monetary", 35000)
		setVehicleHandling(element, "modelFlags", 0x400000)
		setVehicleHandling(element, "handlingFlags", 0x12010000)
		setVehicleHandling(element, "headLight", 0)
		setVehicleHandling(element, "tailLight", 1)
		setVehicleHandling(element, "animGroup", 0)
	elseif getElementModel(element) == 589 then
		setVehicleHandling(element, "mass", 2600)
		setVehicleHandling(element, "turnMass", 4700)
		setVehicleHandling(element, "dragCoeff", 2)
		setVehicleHandling(element, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(element, "percentSubmerged", 75)
		setVehicleHandling(element, "tractionMultiplier", 1.27)
		setVehicleHandling(element, "tractionLoss", 0.85)
		setVehicleHandling(element, "tractionBias", 0.49)
		setVehicleHandling(element, "numberOfGears", 5)
		setVehicleHandling(element, "maxVelocity", 224)
		setVehicleHandling(element, "engineAcceleration", 55)
		setVehicleHandling(element, "engineInertia", 44)
		setVehicleHandling(element, "driveType", "awd")
		setVehicleHandling(element, "engineType", "petrol")
		setVehicleHandling(element, "brakeDeceleration", 181)
		setVehicleHandling(element, "ABS", false)
		setVehicleHandling(element, "steeringLock", 50.0)
		setVehicleHandling(element, "suspensionForceLevel", 0.7)
		setVehicleHandling(element, "suspensionDamping", 0.14)
		setVehicleHandling(element, "suspensionHighSpeedDamping", 0.01)
		setVehicleHandling(element, "suspensionUpperLimit", 0.30)
		setVehicleHandling(element, "suspensionLowerLimit", -0.28)
		setVehicleHandling(element, "suspensionFrontRearBias", 0.52)
		setVehicleHandling(element, "suspensionAntiDiveMultiplier", 0.444)
		setVehicleHandling(element, "seatOffsetDistance", 0.169)
		setVehicleHandling(element, "collisionDamageMultiplier", 0.62)
		setVehicleHandling(element, "monetary", 35000)
		setVehicleHandling(element, "modelFlags", 0x400000)
		setVehicleHandling(element, "handlingFlags", 0x12010000)
		setVehicleHandling(element, "headLight", 0)
		setVehicleHandling(element, "tailLight", 1)
		setVehicleHandling(element, "animGroup", 0)
	elseif getElementModel(element) == 580 then
		setVehicleHandling(element, "mass", 2600)
		setVehicleHandling(element, "turnMass", 4700)
		setVehicleHandling(element, "dragCoeff", 2)
		setVehicleHandling(element, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(element, "percentSubmerged", 75)
		setVehicleHandling(element, "tractionMultiplier", 1.27)
		setVehicleHandling(element, "tractionLoss", 0.85)
		setVehicleHandling(element, "tractionBias", 0.49)
		setVehicleHandling(element, "numberOfGears", 5)
		setVehicleHandling(element, "maxVelocity", 224)
		setVehicleHandling(element, "engineAcceleration", 20)
		setVehicleHandling(element, "engineInertia", 20)
		setVehicleHandling(element, "driveType", "awd")
		setVehicleHandling(element, "engineType", "petrol")
		setVehicleHandling(element, "brakeDeceleration", 50)
		setVehicleHandling(element, "ABS", false)
		setVehicleHandling(element, "steeringLock", 30.0)
		setVehicleHandling(element, "suspensionForceLevel", 0.7)
		setVehicleHandling(element, "suspensionDamping", 0.14)
		setVehicleHandling(element, "suspensionHighSpeedDamping", 0.01)
		setVehicleHandling(element, "suspensionUpperLimit", 0.30)
		setVehicleHandling(element, "suspensionLowerLimit", -0.28)
		setVehicleHandling(element, "suspensionFrontRearBias", 0.52)
		setVehicleHandling(element, "suspensionAntiDiveMultiplier", 0.444)
		setVehicleHandling(element, "seatOffsetDistance", 0.169)
		setVehicleHandling(element, "collisionDamageMultiplier", 0.62)
		setVehicleHandling(element, "monetary", 35000)
		setVehicleHandling(element, "modelFlags", 0x00002000)
		setVehicleHandling(element, "headLight", 0)
		setVehicleHandling(element, "tailLight", 1)
		setVehicleHandling(element, "animGroup", 0)
	elseif getElementModel(element) == 411 then
		setVehicleHandling(element, "mass", 1600)
		setVehicleHandling(element, "turnMass", 3000)
		setVehicleHandling(element, "dragCoeff", 1.8)
		setVehicleHandling(element, "centerOfMass", { 0, 0.50, -0.3 } )
		setVehicleHandling(element, "percentSubmerged", 75)
		setVehicleHandling(element, "tractionMultiplier", 1.05)
		setVehicleHandling(element, "tractionLoss", 0.9)
		setVehicleHandling(element, "tractionBias", 0.497)
		setVehicleHandling(element, "numberOfGears", 5)
		setVehicleHandling(element, "maxVelocity", 230)
		setVehicleHandling(element, "engineAcceleration", 50)
		setVehicleHandling(element, "engineInertia", 60)
		setVehicleHandling(element, "driveType", "awd")
		setVehicleHandling(element, "engineType", "petrol")
		setVehicleHandling(element, "brakeDeceleration", 85)
		setVehicleHandling(element, "ABS", false)
		setVehicleHandling(element, "steeringLock", 45)
		setVehicleHandling(element, "modelFlags", 0x00002000)
		setVehicleHandling(element, "headLight", 0)
		setVehicleHandling(element, "tailLight", 1)
		setVehicleHandling(element, "animGroup", 0)
		setVehicleHandling(element, "suspensionForceLevel", 1.1)
		--setVehicleHandling(element, "suspensionUpperLimit", 0.38)
		setVehicleHandling(element, "suspensionLowerLimit", -0.2)
		setVehicleHandling(element, "suspensionHighSpeedDamping", 0.1)
		setVehicleHandling(element, "suspensionDamping", -0.05)
	elseif getElementModel(element) == 477 then
		setVehicleHandling(element, "mass", 1600)
		setVehicleHandling(element, "turnMass", 3000)
		setVehicleHandling(element, "dragCoeff", 1.8)
		setVehicleHandling(element, "centerOfMass", { 0, 0.50, -0.3 } )
		setVehicleHandling(element, "percentSubmerged", 75)
		setVehicleHandling(element, "tractionMultiplier", 1.05)
		setVehicleHandling(element, "tractionLoss", 1.1)
		setVehicleHandling(element, "tractionBias", 0.497)
		setVehicleHandling(element, "numberOfGears", 5)
		setVehicleHandling(element, "maxVelocity", 230)
		setVehicleHandling(element, "engineAcceleration", 50)
		setVehicleHandling(element, "engineInertia", 60)
		setVehicleHandling(element, "driveType", "awd")
		setVehicleHandling(element, "engineType", "petrol")
		setVehicleHandling(element, "brakeDeceleration", 85)
		setVehicleHandling(element, "ABS", false)
		setVehicleHandling(element, "steeringLock", 45)
		setVehicleHandling(element, "modelFlags", 0x00002000)
		setVehicleHandling(element, "modelFlags", "C0000804")
		setVehicleHandling(element, "headLight", 0)
		setVehicleHandling(element, "tailLight", 1)
		setVehicleHandling(element, "animGroup", 0)
		setVehicleHandling(element, "suspensionForceLevel", 1.1)
		--setVehicleHandling(element, "suspensionUpperLimit", 0.38)
		setVehicleHandling(element, "suspensionLowerLimit", -0.1)
		setVehicleHandling(element, "suspensionHighSpeedDamping", 0.5)
		--setVehicleHandling(element, "suspensionDamping", )
	elseif getElementModel(element) == 558 then
		setVehicleHandling(element, "mass", 1600)
		setVehicleHandling(element, "turnMass", 3000)
		setVehicleHandling(element, "dragCoeff", 1.8)
		setVehicleHandling(element, "centerOfMass", { 0, 0.50, -0.3 } )
		setVehicleHandling(element, "percentSubmerged", 75)
		setVehicleHandling(element, "tractionMultiplier", 1.05)
		setVehicleHandling(element, "tractionLoss", 1.1)
		setVehicleHandling(element, "tractionBias", 0.497)
		setVehicleHandling(element, "numberOfGears", 5)
		setVehicleHandling(element, "maxVelocity", 240)
		setVehicleHandling(element, "engineAcceleration", 40)
		setVehicleHandling(element, "engineInertia", 60)
		setVehicleHandling(element, "driveType", "awd")
		setVehicleHandling(element, "engineType", "petrol")
		setVehicleHandling(element, "brakeDeceleration", 85)
		setVehicleHandling(element, "ABS", false)
		setVehicleHandling(element, "steeringLock", 45)
		setVehicleHandling(element, "modelFlags", 0x00002000)
		setVehicleHandling(element, "headLight", 0)
		setVehicleHandling(element, "tailLight", 1)
		setVehicleHandling(element, "animGroup", 0)
		setVehicleHandling(element, "suspensionForceLevel", 1.1)
		--setVehicleHandling(element, "suspensionUpperLimit", 0.38)
		setVehicleHandling(element, "suspensionLowerLimit", -0.1)
		setVehicleHandling(element, "suspensionHighSpeedDamping", 0.5)
		--setVehicleHandling(element, "suspensionDamping", )
	elseif getElementModel(element) == 579 then
		setVehicleHandling(element, "mass", 1600)
		setVehicleHandling(element, "turnMass", 3000)
		setVehicleHandling(element, "dragCoeff", 1.8)
		setVehicleHandling(element, "centerOfMass", { 0, 0.50, -0.3 } )
		setVehicleHandling(element, "percentSubmerged", 75)
		setVehicleHandling(element, "tractionMultiplier", 1.05)
		setVehicleHandling(element, "tractionLoss", 1.1)
		setVehicleHandling(element, "tractionBias", 0.497)
		setVehicleHandling(element, "numberOfGears", 5)
		setVehicleHandling(element, "maxVelocity", 240)
		setVehicleHandling(element, "engineAcceleration", 40)
		setVehicleHandling(element, "engineInertia", 60)
		setVehicleHandling(element, "driveType", "awd")
		setVehicleHandling(element, "engineType", "petrol")
		setVehicleHandling(element, "brakeDeceleration", 85)
		setVehicleHandling(element, "ABS", false)
		setVehicleHandling(element, "steeringLock", 45)
		setVehicleHandling(element, "modelFlags", 0x00002000)
		setVehicleHandling(element, "headLight", 0)
		setVehicleHandling(element, "tailLight", 1)
		setVehicleHandling(element, "animGroup", 0)
		setVehicleHandling(element, "suspensionForceLevel", 1.1)
		--setVehicleHandling(element, "suspensionUpperLimit", 0.38)
		setVehicleHandling(element, "suspensionLowerLimit", -0.1)
		setVehicleHandling(element, "suspensionHighSpeedDamping", 0.5)
		--setVehicleHandling(element, "suspensionDamping", )
	elseif getElementModel(element) == 559 then
		setVehicleHandling(element, "mass", 1600)
		setVehicleHandling(element, "turnMass", 3000)
		setVehicleHandling(element, "dragCoeff", 1.8)
		setVehicleHandling(element, "centerOfMass", { 0, 0.50, -0.3 } )
		setVehicleHandling(element, "percentSubmerged", 75)
		setVehicleHandling(element, "tractionMultiplier", 1.05)
		setVehicleHandling(element, "tractionLoss", 1.1)
		setVehicleHandling(element, "tractionBias", 0.497)
		setVehicleHandling(element, "numberOfGears", 5)
		setVehicleHandling(element, "maxVelocity", 240)
		setVehicleHandling(element, "engineAcceleration", 40)
		setVehicleHandling(element, "engineInertia", 60)
		setVehicleHandling(element, "driveType", "awd")
		setVehicleHandling(element, "engineType", "petrol")
		setVehicleHandling(element, "brakeDeceleration", 85)
		setVehicleHandling(element, "ABS", false)
		setVehicleHandling(element, "steeringLock", 45)
		setVehicleHandling(element, "modelFlags", "C0000804")
		setVehicleHandling(element, "headLight", 0)
		setVehicleHandling(element, "tailLight", 1)
		setVehicleHandling(element, "animGroup", 0)
		setVehicleHandling(element, "suspensionForceLevel", 1.1)
		setVehicleHandling(element, "suspensionLowerLimit", 0)
		setVehicleHandling(element, "suspensionHighSpeedDamping", 0.5)
	elseif getElementModel(element) == 494 then
		setVehicleHandling(element, "mass", 2000)
		setVehicleHandling(element, "turnMass", 3500)
		setVehicleHandling(element, "dragCoeff", 1.8)
		setVehicleHandling(element, "centerOfMass", { 0, 0.50, -0.3 } )
		setVehicleHandling(element, "percentSubmerged", 75)
		setVehicleHandling(element, "tractionMultiplier", 1.05)
		setVehicleHandling(element, "tractionLoss", 1.1)
		setVehicleHandling(element, "tractionBias", 0.497)
		setVehicleHandling(element, "numberOfGears", 5)
		setVehicleHandling(element, "maxVelocity", 240)
		setVehicleHandling(element, "engineAcceleration", 30)
		setVehicleHandling(element, "engineInertia", 40)
		setVehicleHandling(element, "driveType", "awd")
		setVehicleHandling(element, "engineType", "petrol")
		setVehicleHandling(element, "brakeDeceleration", 85)
		setVehicleHandling(element, "ABS", false)
		setVehicleHandling(element, "steeringLock", 45)
		setVehicleHandling(element, "modelFlags", 0x00002000)
		setVehicleHandling(element, "headLight", 0)
		setVehicleHandling(element, "tailLight", 1)
		setVehicleHandling(element, "animGroup", 0)
		setVehicleHandling(element, "suspensionForceLevel", 1.2)
		--setVehicleHandling(element, "suspensionUpperLimit", 0.38)
		setVehicleHandling(element, "suspensionLowerLimit", -0.1)
		setVehicleHandling(element, "suspensionHighSpeedDamping", -0.5)
		--setVehicleHandling(element, "suspensionDamping", )
	else
		setVehicleHandling(element, "mass", 1500)
		setVehicleHandling(element, "turnMass", 2800)
		setVehicleHandling(element, "dragCoeff", 1)
		setVehicleHandling(element, "centerOfMass", { 0.07, 0.173333333, -0.2444 } )
		setVehicleHandling(element, "percentSubmerged", 21)
		setVehicleHandling(element, "tractionMultiplier", 1.477)
		setVehicleHandling(element, "tractionLoss", 0.494323)
		setVehicleHandling(element, "tractionBias", 0.4577)
		setVehicleHandling(element, "numberOfGears", 5)
		setVehicleHandling(element, "maxVelocity", 194)
		setVehicleHandling(element, "engineAcceleration", 37.7)
		setVehicleHandling(element, "engineInertia", 40)
		setVehicleHandling(element, "driveType", "awd")
		setVehicleHandling(element, "engineType", "petrol")
		setVehicleHandling(element, "brakeDeceleration", 46)
		setVehicleHandling(element, "ABS", false)
		setVehicleHandling(element, "steeringLock", 50.0)
		setVehicleHandling(element, "seatOffsetDistance", 0.5)
		setVehicleHandling(element, "collisionDamageMultiplier", 0.60)
	end
end

function onEnter(veh)
	if isElement(veh) and isElement(source) then
		loadHandling(veh)
	end
end
addEventHandler("onPlayerVehicleEnter", root, onEnter)

function onChange(key, oval, nval)
	if key == "a.Driftmode" and nval == "off" then
		if isPedInVehicle(source) then
			local veh = getPedOccupiedVehicle(source)
			loadHandling(veh)
		end
	end
end
addEventHandler("onElementDataChange", root, onChange)